# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 15 Dec 2020 13:32:39 +0000
*               @ALL          0
*               @user         8
