<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 15 Dec 2020 13:32:39 +0000
 */
$conf['title'] = 'New Animal';
$conf['lang'] = 'pl';
$conf['license'] = '';
$conf['showuseras'] = 'username';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
