# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 15 Dec 2020 13:32:39 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$OYYT335K4uJsz5qY4TpF1OUeto3eqS0txs55IWYiQh/WaRTuahedq:Admin:admin@admin:admin,user
